- docs/openapi.yaml
以下會有查詢到學年/學期
`/user/scores`
`/user/midterm-alerts`
`/user/reward-and-penalty`
`/user​/coursetable`
可能會有畢業查不到資料，或者是像是沒得獎沒成績發生
都新增204  status_code上去
在`/user/reward-and-penalty` 中有一個回傳"type"的schema的type錯誤
應該為string，錯誤為int，在此順便修正
> Issue#6 補充status code

- src/view/user.py
#20 
修復錯誤的parameter
`value` >> `semester`
> Fix parameter error

- README.md
> Add link of api page

- docs/openapi.yaml
> 更新API文件 (校車)

- src/cache/school_announcements_cache.py
- src/view/news.py
> 修復學校最新消息，頁數從1開始

- src/view/bus.py
根據`document/issue#13` 做修正
測試伺服器已經更新
> Issue#13 預約校車response

- docs/openapi.yaml
錯誤種類繁多
基本統一400跟403
再透過回傳的json內的`code` 提供判斷
> 請假提交/請假資訊 文件更新

- docs/openapi.yaml
將`delayReason` 更變為 `delayReasonText`
> 請假提交 文件更新 

- docs/openapi.yaml
> 修正 leaves 字眼至 leave  文件部分

- src/cache/leave_cache.py
> 請假申請 爬蟲選擇日期出錯

- src/view/leave.py
遺漏commit
`leavesProof` >> `proofImage `
> 修正 leaves 字眼至 leave

- src/view/leave.py
> 支持 mutlipart 小寫MIME格式

- src/news/news.py
> 修復最新消息在過期時間為負數的錯誤，以及顯示過期時間

- src/crawler/leave_crawler.py
#76 
測試後，學校那邊沒辦法接受 不需要延遲理由，卻填寫理由的狀況
正式伺服器已經更新上去
> 修復#76 請假申請失敗的問題

- src/crawler/school_announcements_crawler.py
> Fix announcement parser

- src/cache/leave_cache.py
- src/view/leave.py
> 修復 請假不附帶證明發生錯誤

- src/cache/leave_cache.py
> Fix the section 5 leave error

- src/cache/parse.py
> 學期成績新增系排欄位並移除班名次百分比

- src/crawler/leave_crawler.py
#103 
學校把`C`節移除導致爆炸
html欄位前一個欄位不變的情況下，可以動態調整欄位長度
> 修復請假-假單查詢失敗問題 

- Dockerfile
- requirements.txt
- src/crawler/bus_crawler.py
- src/crawler/bus_encypt.py
雖然用不到了
解決長久的效能痛點
移除NdeJS 減少大小&加快Docker build
> bus login encrypt 
